apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  namespace: default
  annotations:
    backstage.io/managed-by-location: group-https://app.harness.io/
    backstage.io/managed-by-origin-location: group-https://app.harness.io/
  name: access-test
  title: access-test
  created_by: Harness
  uid: 6607d329-2b48-484e-a84e-5a71641fafb6
  etag: 35f86ff68f6e7e64a7071ba2fa24d257ba926aa1
relations: []
spec:
  type: team
  children: []
  members: []
