apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  namespace: default
  name: agniva.banerjee
  title: agniva.banerjee
  uid: b444cfb4-fa76-4964-ace5-3152ab475d21
  etag: 2e2e49a0e6154e0d461043a4daf6641ee5bb928a
spec:
  profile:
    displayName: agniva.banerjee
    email: agniva.banerjee@harness.io
  memberOf:
    - group:default/harness_account_all_users
